# Generated by Django 4.1 on 2022-10-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=255)),
                ('edad', models.IntegerField(null=True)),
                ('genero', models.CharField(max_length=1)),
            ],
        ),
    ]
